### ISSUE TITLE
Registry returned 404

### ISSUE THREAD

**Issue by mmintel** [michaelzoidl/babel-root-import#23]
hi there, 

I am getting a strange error in my project. After starting the npm dev server its trying to install the plugin. However it's searching for "babel-plugin-babel-root-import", which, of course, doesn't exist.

This is the log
```BASH
Installing babel-plugin-babel-root-import...
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   'babel-plugin-babel-root-import' ]
npm info using npm@3.9.3
npm info using node@v5.11.1
npm verb request uri https://registry.npmjs.org/babel-plugin-babel-root-import
npm verb request no auth needed
npm info attempt registry request try #1 at 14:23:45
npm verb request id 7e6f343b96f6bb6b
npm http request GET https://registry.npmjs.org/babel-plugin-babel-root-import
npm http 404 https://registry.npmjs.org/babel-plugin-babel-root-import
npm verb headers { 'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=0',
npm verb headers   'content-length': '2',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Mon, 30 May 2016 12:23:49 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-ams4126-AMS',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1464611029.006618,VS0,VE98',
npm verb headers   vary: 'Accept-Encoding' }
npm verb stack Error: Registry returned 404 for GET on https://registry.npmjs.org/babel-plugin-babel-root-import
npm verb stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
npm verb stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
npm verb stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
npm verb stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:200:22)
npm verb stack     at emitTwo (events.js:100:13)
npm verb stack     at Request.emit (events.js:185:7)
npm verb stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1067:10)
npm verb stack     at emitOne (events.js:95:20)
npm verb stack     at Request.emit (events.js:182:7)
npm verb stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:988:12)
npm verb statusCode 404
npm verb pkgid babel-plugin-babel-root-import
npm verb cwd /Users/mmintel/Projekte/prismic-react
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "babel-plugin-babel-root-import"
npm ERR! node v5.11.1
npm ERR! npm  v3.9.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/babel-plugin-babel-root-import
npm ERR! 404
npm ERR! 404  'babel-plugin-babel-root-import' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit [ 1, true ]
```

I used this project over here as a starter for my own https://github.com/stephmilovic/prismic-react and had this error from the beginning.. however the author is not answering my issue so I am  trying my luck over here.

Thats my .babelrc:
```
{
  "presets": ["react", "es2015"],
  "env": {
    "development": {
      "presets": ["react-hmre"]
    }
  },
  "plugins": [
    "babel-root-import"
  ]
}
```

and that's the part of my webpack config:
```
{
        test: /\.jsx?$/,
        loader: 'babel-loader',
        exclude: /(node_modules|bower_components)/
      }
```
Do you have any idea?

Thanks!

**Comment by michaelzoidl** [comment]
Same Issue in #20 ... i'm still searching for the problem - that should be some breaking change in babel itself... 

Short: At this moment i've no idea... i try to find a solution ASAP

**Comment by michaelzoidl** [comment]
@mmintel did you found some solution? didn't hear some again from this bug...

**Comment by mmintel** [comment]
No, still the same problem..

**Comment by michaelzoidl** [comment]
hm.. 
I can't reproduce it.. the error message comes up when you try to install this plugin?

**Comment by michaelzoidl** [comment]
Since there is no activity anymore i close this (still cannot reproduce)
