### ISSUE TITLE
Doesn't work with npm link?

### ISSUE THREAD

**Issue by olalonde** [michaelzoidl/babel-root-import#54]
I'm getting a weird error after `npm link`ing a dependency:

```
[1] [piping] error given was: ReferenceError: Unknown plugin "babel-root-import" specified in "base" at 0, attempted to resolve relative to "/Users/olalonde/code/blockai/filepunk-widget/lib"
[1]     at /Users/olalonde/code/blockai/blockai-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:204:17
[1]     at Array.map (native)
[1]     at Function.normalisePlugins (/Users/olalonde/code/blockai/blockai-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
[1]     at OptionManager.mergeOptions (/Users/olalonde/code/blockai/blockai-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300
```

**Comment by olalonde** [comment]
Oops, looks like an issue with webpack or babel (https://github.com/babel/babel/issues/4693)
